import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Wind, ExternalLink, Info, Droplets, Sun, Flower2 } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { LiveIndicator } from '@components/shared/LiveIndicator';
import { LanguageSelector } from '@/components/ui/LanguageSelector';
import { getAqiBands, getUVLevels, getPollenLevels, getPollutantInfo, getDataSources } from '@utils/aqiInfo';
const POLLUTANTS_ORDER = ['pm25', 'pm10', 'no2', 'o3', 'co'];
export const GlossaryPage = () => {
    const { t } = useTranslation();
    const aqiBands = getAqiBands(t);
    const uvLevels = getUVLevels(t);
    const pollenLevels = getPollenLevels(t);
    const pollutantInfo = getPollutantInfo(t);
    const dataSources = getDataSources(t);
    const navLinks = [
        { to: '/', label: t('nav.dashboard') },
        { to: '/ranking', label: t('nav.ranking') },
        { to: '/mapa-queimadas', label: t('nav.fireMap') },
        { to: '/guia', label: t('nav.guide') },
    ];
    return (_jsxs("div", { className: "grain-overlay min-h-screen bg-background relative overflow-hidden", children: [_jsx("div", { className: "ambient-blob blob-cyan", style: { top: '-200px', left: '-100px' } }), _jsx("div", { className: "ambient-blob blob-blue", style: { bottom: '-150px', right: '-100px' } }), _jsx("header", { className: "fixed top-0 left-0 right-0 z-40 bg-card/80 backdrop-blur-xl border-b border-border", children: _jsxs("div", { className: "flex items-center justify-between px-6 py-3 max-w-[1400px] mx-auto gap-4", children: [_jsxs(Link, { to: "/", className: "flex items-center gap-2 shrink-0", children: [_jsx(Wind, { className: "w-6 h-6 text-primary" }), _jsxs("span", { className: "font-heading text-2xl tracking-wider text-foreground", children: ["Respir", _jsx("span", { className: "text-primary", children: "A" })] }), _jsx("span", { className: "text-xs font-mono text-muted-foreground ml-2 hidden sm:block", children: "AirBR" })] }), _jsx("nav", { className: "hidden md:flex items-center gap-0.5", children: navLinks.map(link => (_jsx(Link, { to: link.to, className: `px-3 py-1.5 text-xs font-body rounded transition-colors ${link.to === '/guia'
                                    ? 'text-primary border-b border-primary font-semibold'
                                    : 'text-muted-foreground hover:text-foreground hover:bg-muted'}`, children: link.label }, link.to))) }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(LanguageSelector, {}), _jsx(LiveIndicator, {})] })] }) }), _jsxs("main", { className: "pt-20 pb-12 px-4 max-w-[900px] mx-auto relative z-10", children: [_jsxs("div", { className: "mb-10", children: [_jsx("h1", { className: "font-heading text-4xl sm:text-5xl tracking-wide text-foreground", children: t('glossary.title') }), _jsx("p", { className: "text-sm text-muted-foreground font-body mt-2", children: t('glossary.subtitle') })] }), _jsxs("section", { className: "mb-10", id: "aqi", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx(Info, { className: "w-4 h-4 text-primary" }), _jsx("h2", { className: "font-heading text-2xl tracking-wide text-foreground", children: t('glossary.whatIsAqi') })] }), _jsx("p", { className: "text-xs font-mono text-muted-foreground mb-4", children: t('glossary.aqiSubtitle') }), _jsx("p", { className: "text-sm font-body text-muted-foreground mb-4 leading-relaxed", children: t('glossary.aqiDesc1') }), _jsx("p", { className: "text-sm font-body text-muted-foreground mb-6 leading-relaxed", children: t('glossary.aqiDesc2') }), _jsx("div", { className: "space-y-2", children: aqiBands.map(band => (_jsxs("div", { className: "flex items-start gap-3 bg-card border border-border rounded p-3", children: [_jsx("div", { className: "shrink-0 w-14 text-center rounded py-1", style: { background: `${band.color}20`, color: band.color }, children: _jsxs("span", { className: "font-mono font-bold text-sm block", children: [band.min, "\u2013", band.max === 500 ? '500+' : band.max] }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("div", { className: "flex items-center gap-2 mb-0.5", children: _jsx("span", { className: "text-xs font-body font-semibold px-2 py-0.5 rounded-full uppercase tracking-wide", style: { background: `${band.color}20`, color: band.color }, children: band.label }) }), _jsx("p", { className: "text-xs font-body text-muted-foreground", children: band.healthImpact }), _jsx("p", { className: "text-xs font-mono text-muted-foreground/60 mt-0.5", children: band.recommendation })] })] }, band.label))) })] }), _jsxs("section", { className: "mb-10", id: "poluentes", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx(Droplets, { className: "w-4 h-4 text-primary" }), _jsx("h2", { className: "font-heading text-2xl tracking-wide text-foreground", children: t('glossary.pollutants') })] }), _jsx("p", { className: "text-xs font-mono text-muted-foreground mb-4", children: t('glossary.pollutantsSubtitle') }), _jsx("div", { className: "grid grid-cols-1 gap-4", children: POLLUTANTS_ORDER.map(key => {
                                    const p = pollutantInfo[key];
                                    return (_jsxs("div", { className: "bg-card border border-border rounded p-4", children: [_jsxs("div", { className: "flex items-start justify-between gap-3 mb-3", children: [_jsxs("div", { children: [_jsx("span", { className: "font-mono font-bold text-lg text-foreground", children: p.label }), _jsx("span", { className: "text-xs text-muted-foreground font-body ml-2", children: p.fullName })] }), _jsxs("div", { className: "shrink-0 text-right", children: [_jsx("span", { className: "text-xs font-mono text-muted-foreground block", children: t('glossary.whoLimit') }), _jsxs("span", { className: "font-mono font-bold text-primary", children: [p.whoLimit, " ", p.unit] }), _jsx("span", { className: "text-[10px] text-muted-foreground block", children: p.whoLimitPeriod })] })] }), _jsxs("div", { className: "space-y-2 text-sm font-body text-muted-foreground leading-relaxed", children: [_jsx("p", { children: p.description }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1", children: [_jsxs("div", { className: "bg-muted/40 border border-border/50 rounded p-2.5", children: [_jsx("p", { className: "text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1", children: t('glossary.mainSources') }), _jsx("p", { className: "text-xs", children: p.sources })] }), _jsxs("div", { className: "bg-muted/40 border border-border/50 rounded p-2.5", children: [_jsx("p", { className: "text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1", children: t('glossary.healthEffects') }), _jsx("p", { className: "text-xs", children: p.effects })] })] })] })] }, key));
                                }) })] }), _jsxs("section", { className: "mb-10", id: "uv", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx(Sun, { className: "w-4 h-4 text-primary" }), _jsx("h2", { className: "font-heading text-2xl tracking-wide text-foreground", children: t('glossary.uvIndex') })] }), _jsx("p", { className: "text-xs font-mono text-muted-foreground mb-3", children: t('glossary.uvSubtitle') }), _jsx("p", { className: "text-sm font-body text-muted-foreground mb-4 leading-relaxed", children: t('glossary.uvDesc') }), _jsx("div", { className: "overflow-hidden rounded border border-border", children: _jsxs("table", { className: "w-full text-xs font-body", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-muted/60 border-b border-border", children: [_jsx("th", { className: "text-left px-3 py-2 font-mono text-muted-foreground uppercase tracking-wider", children: t('glossary.range') }), _jsx("th", { className: "text-left px-3 py-2 font-mono text-muted-foreground uppercase tracking-wider", children: t('glossary.classification') }), _jsx("th", { className: "text-left px-3 py-2 font-mono text-muted-foreground uppercase tracking-wider hidden sm:table-cell", children: t('glossary.recommendation') })] }) }), _jsx("tbody", { children: uvLevels.map((level, i) => {
                                                const min = i === 0 ? 0 : uvLevels[i - 1].max + 1;
                                                return (_jsxs("tr", { className: "border-b border-border last:border-0 bg-card hover:bg-muted/30 transition-colors", children: [_jsxs("td", { className: "px-3 py-2.5 font-mono", style: { color: level.color }, children: [min, "\u2013", level.max === 11 ? '11+' : level.max] }), _jsx("td", { className: "px-3 py-2.5", children: _jsx("span", { className: "px-2 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wide", style: { background: `${level.color}20`, color: level.color }, children: level.label }) }), _jsx("td", { className: "px-3 py-2.5 text-muted-foreground hidden sm:table-cell", children: level.recommendation })] }, level.label));
                                            }) })] }) })] }), _jsxs("section", { className: "mb-10", id: "polen", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx(Flower2, { className: "w-4 h-4 text-primary" }), _jsx("h2", { className: "font-heading text-2xl tracking-wide text-foreground", children: t('glossary.pollenLevel') })] }), _jsx("p", { className: "text-xs font-mono text-muted-foreground mb-3", children: t('glossary.pollenSubtitle') }), _jsx("p", { className: "text-sm font-body text-muted-foreground mb-4 leading-relaxed", children: t('glossary.pollenDesc') }), _jsx("div", { className: "overflow-hidden rounded border border-border", children: _jsxs("table", { className: "w-full text-xs font-body", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-muted/60 border-b border-border", children: [_jsx("th", { className: "text-left px-3 py-2 font-mono text-muted-foreground uppercase tracking-wider", children: t('glossary.range') }), _jsx("th", { className: "text-left px-3 py-2 font-mono text-muted-foreground uppercase tracking-wider", children: t('glossary.classification') }), _jsx("th", { className: "text-left px-3 py-2 font-mono text-muted-foreground uppercase tracking-wider hidden sm:table-cell", children: t('glossary.recommendation') })] }) }), _jsx("tbody", { children: pollenLevels.map((level, i) => {
                                                const min = i === 0 ? 0 : pollenLevels[i - 1].max + 1;
                                                return (_jsxs("tr", { className: "border-b border-border last:border-0 bg-card hover:bg-muted/30 transition-colors", children: [_jsxs("td", { className: "px-3 py-2.5 font-mono", style: { color: level.color }, children: [min, "\u2013", level.max] }), _jsx("td", { className: "px-3 py-2.5", children: _jsx("span", { className: "px-2 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wide", style: { background: `${level.color}20`, color: level.color }, children: level.label }) }), _jsx("td", { className: "px-3 py-2.5 text-muted-foreground hidden sm:table-cell", children: level.recommendation })] }, level.label));
                                            }) })] }) })] }), _jsxs("section", { className: "mb-10", id: "fontes", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx(ExternalLink, { className: "w-4 h-4 text-primary" }), _jsx("h2", { className: "font-heading text-2xl tracking-wide text-foreground", children: t('glossary.dataSources') })] }), _jsx("p", { className: "text-xs font-mono text-muted-foreground mb-4", children: t('glossary.dataSourcesSubtitle') }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-3", children: dataSources.map(source => (_jsxs("a", { href: source.url, target: "_blank", rel: "noopener noreferrer", className: "group bg-card border border-border rounded p-4 hover:border-primary/40 hover:bg-muted/30 transition-all", children: [_jsxs("div", { className: "flex items-start justify-between gap-2 mb-1.5", children: [_jsx("span", { className: "text-xs font-body font-semibold text-foreground group-hover:text-primary transition-colors leading-snug", children: source.name }), _jsx(ExternalLink, { className: "w-3 h-3 shrink-0 text-muted-foreground group-hover:text-primary transition-colors mt-0.5" })] }), _jsx("p", { className: "text-xs font-body text-muted-foreground leading-relaxed", children: source.description })] }, source.name))) })] }), _jsx("footer", { className: "mt-10 text-xs text-muted-foreground text-center font-mono border-t border-border pt-6", children: t('glossary.footer') })] })] }));
};
