import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { getAQIColor } from '@data/mockCities';
import { MapPin } from 'lucide-react';
import { OmsComplianceBadge } from './OmsComplianceBadge';
export const RankingTable = ({ cities, onCityClick, isMobile = false }) => {
    if (isMobile) {
        return (_jsx("div", { className: "space-y-2", children: cities.map((city, idx) => {
                const color = getAQIColor(city.aqi);
                const pm25 = city.pollutants.find(p => p.key === 'pm25');
                return (_jsxs("button", { onClick: () => onCityClick?.(city.name), className: "w-full bg-card border border-border rounded p-3 flex items-center gap-3 hover:border-primary/30 transition-colors text-left", children: [_jsxs("span", { className: "w-7 text-center font-mono text-sm text-muted-foreground shrink-0", children: ["#", idx + 1] }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "font-body font-semibold text-foreground text-sm truncate", children: city.name }), _jsxs("p", { className: "text-xs text-muted-foreground font-mono", children: [city.state, " \u00B7 ", city.region] })] }), _jsxs("div", { className: "flex flex-col items-end gap-1 shrink-0", children: [_jsx("span", { className: "font-mono font-bold text-base", style: { color }, children: city.aqi }), _jsx(OmsComplianceBadge, { compliant: city.omsCompliant })] })] }, city.name));
            }) }));
    }
    return (_jsx("div", { className: "overflow-x-auto rounded border border-border", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-muted/60 border-b border-border", children: [_jsx("th", { className: "text-left px-4 py-3 font-mono text-xs text-muted-foreground uppercase tracking-wider w-12", children: "#" }), _jsx("th", { className: "text-left px-4 py-3 font-mono text-xs text-muted-foreground uppercase tracking-wider", children: "Cidade" }), _jsx("th", { className: "text-left px-4 py-3 font-mono text-xs text-muted-foreground uppercase tracking-wider", children: "Estado" }), _jsx("th", { className: "text-left px-4 py-3 font-mono text-xs text-muted-foreground uppercase tracking-wider", children: "Regi\u00E3o" }), _jsx("th", { className: "text-right px-4 py-3 font-mono text-xs text-muted-foreground uppercase tracking-wider", children: "AQI" }), _jsx("th", { className: "text-right px-4 py-3 font-mono text-xs text-muted-foreground uppercase tracking-wider", children: "PM2.5" }), _jsx("th", { className: "text-center px-4 py-3 font-mono text-xs text-muted-foreground uppercase tracking-wider", children: "OMS" })] }) }), _jsx("tbody", { children: cities.map((city, idx) => {
                        const color = getAQIColor(city.aqi);
                        const pm25 = city.pollutants.find(p => p.key === 'pm25');
                        return (_jsxs("tr", { onClick: () => onCityClick?.(city.name), className: `border-b border-border/50 transition-colors ${onCityClick ? 'cursor-pointer hover:bg-muted/40' : ''}`, children: [_jsx("td", { className: "px-4 py-3 font-mono text-muted-foreground", children: idx + 1 }), _jsx("td", { className: "px-4 py-3", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(MapPin, { className: "w-3 h-3 text-muted-foreground shrink-0" }), _jsx("span", { className: "font-body font-medium text-foreground", children: city.name })] }) }), _jsx("td", { className: "px-4 py-3 font-mono text-sm text-muted-foreground", children: city.state }), _jsx("td", { className: "px-4 py-3", children: _jsx("span", { className: "text-xs font-body text-muted-foreground", children: city.region }) }), _jsxs("td", { className: "px-4 py-3 text-right", children: [_jsx("span", { className: "font-mono font-bold text-base", style: { color }, children: city.aqi }), _jsx("span", { className: "text-xs text-muted-foreground ml-1 hidden xl:inline", children: city.aqiLabel })] }), _jsx("td", { className: "px-4 py-3 text-right font-mono text-sm text-foreground", children: pm25 ? `${pm25.value} µg/m³` : '—' }), _jsx("td", { className: "px-4 py-3 text-center", children: _jsx(OmsComplianceBadge, { compliant: city.omsCompliant }) })] }, city.name));
                    }) })] }) }));
};
